name: "Archive and Slack: Toronto Globe and Mail"

on:
  workflow_dispatch:
#   schedule:
#     - cron: "0 10,16,22 * * *"

jobs:
  archive-site:
    name: Archive bundle
    uses: palewire/news-homepages/.github/workflows/reusable-archive-single-site-workflow.yml@main
    with:
      handle: globeandmail
    secrets: inherit

  newsroom-slack:
    name: Post to newsroom Slack
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [archive-site]
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: slack
        name: Post to Slack
        uses: ./.github/actions/slack
        with:
          handle: globeandmail
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_GLOBEANDMAIL }}

  palewire-slack:
    name: Post to palewire Slack
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [archive-site]
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v3

      - id: slack
        name: Post to Slack
        uses: ./.github/actions/slack
        with:
          handle: globeandmail
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL_PALEWIRE }}
