name: Update website

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */6 * * *'

concurrency:
  group: site
  cancel-in-progress: true

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    steps:
      - id: checkout
        name: Checkout
        uses: actions/checkout@v4

      - id: setup-python
        name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          cache: 'pipenv'

      - id: install-pipenv
        name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python
        shell: bash

      - id: install-python-dependencies
        name: Install Python dependencies
        run: pipenv sync --dev
        shell: bash

      - id: render-templates
        name: Render site templates
        run: pipenv run make site
        shell: bash

      - id: build-site
        name: Build site
        run: cd _site && pipenv run make html
        shell: bash

      - id: configure-aws
        name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.PALEWIRE_DOCS_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.PALEWIRE_DOCS_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - id: npm-deploy
        name: Upload the prepared files
        uses: datadesk/delivery-deploy-action@v1
        with:
          bucket: ${{ secrets.PALEWIRE_DOCS_AWS_BUCKET }}
          base-path: news-homepages
          dir: _site/_build/html/
          should-cache: false
          use-accelerate-endpoint: false
          public: true
